name: Merge Checks
run-name: PR Checks for ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - trunk-merge/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.lock ]; then pip install -r requirements-dev.lock; fi

      - name: Sleep for 1 minute
        run: sleep 60s
        shell: bash

      - name: Unit Tests
        run: |
          pytest --junit-xml=.test_output/results_test.xml
      - name: Upload results
        # Run this step even if the test step ahead fails
        if: "!cancelled()"
        uses: trunk-io/analytics-uploader@main
        with:
          # Path to your test results.
          junit-paths: .test_output/**/*_test.xml
          # Provide your Trunk organization slug.
          org-slug: dubs0
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_API_TOKEN }}
        continue-on-error: true
